spring:
  datasource:
    url:
    username: u
    password: u
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE